//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAndon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkcenterList
    {
        public string WorkcenterID { get; set; }
        public string WorkcenterName { get; set; }
        public Nullable<int> WorkcenterRow { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string Status3 { get; set; }
        public string Status4 { get; set; }
        public string Status5 { get; set; }
    }
}
